site_name: AI Feedback

nav:
  - Home: index.md
  - About: about.md
  - Student Asks - Biology English Open Ended: "Student Asks/Biology/Comparison.md"
  - Student Asks - Dutch Grammar Closed Ended: "Student Asks/Dutch/Grammar/Comparison.md"
  - Discoveries and Research: "discoveries.md"

theme: 
  name: material
  palette:
    # Dark mode
    - scheme: slate
    # To switch to light mode 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      # accent: red

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font: 
    text: Roboto
  language: en
  features:
  # With anchor tracking the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents. 
    - navigation.tracking
    # Puts nav tabs at the top instead of side, and sticky
    - navigation.tabs
    - navigation.tabs.sticky
    
    # breadcrumb nav 
    - navigation.path
    
    # adds back to top button
    - navigation.top

    # Serch auto completion, accept with right key 
    - search.suggest

    # highlights the search results on the page 
    - search.highlight 

    # add content to codeblocks like special kinds of comments etc 
    - content.code.annotate 

    # allows user to cocpy the code, handy 
    - content.code.copy

    # vergeten
    - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:

  # For code blocks and highlighting
  - pymdownx.highlight:
      # adds ability for linenumbers
      anchor_linenums: true
      # wraps __span id to each cod line element
      line_spans: __span
      # adds language highlighting
      pygments_lang_class: true
  
  # enables admonitions 
  - admonition
  # adds inline code highlighting
  - pymdownx.inlinehilite
  # ability to use include other files in other files
  - pymdownx.snippets
  # adds abiility to nest code and content bloscks inside of eachother 
  - pymdownx.superfences
  # adds ability to add collapsible note blocks/admonitions
  - pymdownx.details
